name: Build PDF from Jupyter Notebook

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container: debian:trixie

    env:
      # Debian Trixie enforces PEP 668. Since this is an ephemeral CI container,
      # we allow pip to install packages system-wide.
      PIP_BREAK_SYSTEM_PACKAGES: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          apt-get update
          apt-get install -y \
            make \
            python3 \
            python3-pip \
            python-is-python3 \
            pandoc \
            texlive-xetex \
            texlive-fonts-recommended \
            texlive-plain-generic

      - name: Install python packages
        run: |
          pip3 install -r requirements.txt

      - name: Convert to PDF
        run: |
          make

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86-64-by-example
          path: x86-64-by-example.pdf
          if-no-files-found: error
